// This file is @generated by prost-build.
#[derive(::serde::Serialize)]
#[derive(::serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceConnectedEvent {
    #[prost(string, optional, tag = "1")]
    pub device_ip_address: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(::serde::Serialize)]
#[derive(::serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceDisconnectedEvent {}
#[derive(::serde::Serialize)]
#[derive(::serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceRegisteredEvent {}
#[derive(::serde::Serialize)]
#[derive(::serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceDeletionStartedEvent {}
#[derive(::serde::Serialize)]
#[derive(::serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeviceDeletionFinishedEvent {}
#[derive(::serde::Serialize)]
#[derive(::serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceErrorEvent {
    #[prost(string, optional, tag = "1")]
    pub error_name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map = "string, string", tag = "2")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IncomingDataEvent {
    #[prost(string, optional, tag = "1")]
    pub interface: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub path: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub bson_value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValueChangeEvent {
    #[prost(string, optional, tag = "1")]
    pub interface: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub path: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub old_bson_value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub new_bson_value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValueChangeAppliedEvent {
    #[prost(string, optional, tag = "1")]
    pub interface: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub path: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub old_bson_value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "4")]
    pub new_bson_value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PathCreatedEvent {
    #[prost(string, optional, tag = "1")]
    pub interface: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub path: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub bson_value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(::serde::Serialize)]
#[derive(::serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PathRemovedEvent {
    #[prost(string, optional, tag = "1")]
    pub interface: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub path: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValueStoredEvent {
    #[prost(string, optional, tag = "1")]
    pub interface: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub path: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub bson_value: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
}
#[derive(::serde::Serialize)]
#[derive(::serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InterfaceVersion {
    #[prost(int32, tag = "1")]
    pub major: i32,
    #[prost(int32, tag = "2")]
    pub minor: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IncomingIntrospectionEvent {
    #[deprecated]
    #[prost(string, optional, tag = "1")]
    pub introspection: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(map = "string, message", tag = "2")]
    pub introspection_map: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        InterfaceVersion,
    >,
}
#[derive(::serde::Serialize)]
#[derive(::serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InterfaceAddedEvent {
    #[prost(string, optional, tag = "1")]
    pub interface: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag = "2")]
    pub major_version: i32,
    #[prost(int32, tag = "3")]
    pub minor_version: i32,
}
#[derive(::serde::Serialize)]
#[derive(::serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InterfaceRemovedEvent {
    #[prost(string, optional, tag = "1")]
    pub interface: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag = "2")]
    pub major_version: i32,
}
#[derive(::serde::Serialize)]
#[derive(::serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InterfaceMinorUpdatedEvent {
    #[prost(string, optional, tag = "1")]
    pub interface: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, tag = "2")]
    pub major_version: i32,
    #[prost(int32, tag = "3")]
    pub old_minor_version: i32,
    #[prost(int32, tag = "4")]
    pub new_minor_version: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SimpleEvent {
    #[deprecated]
    #[prost(int32, tag = "1")]
    pub version: i32,
    #[prost(bytes = "vec", optional, tag = "2")]
    pub simple_trigger_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(bytes = "vec", optional, tag = "3")]
    pub parent_trigger_id: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(string, optional, tag = "4")]
    pub realm: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "5")]
    pub device_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, optional, tag = "18")]
    pub timestamp: ::core::option::Option<i64>,
    #[prost(
        oneof = "simple_event::Event",
        tags = "6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22"
    )]
    pub event: ::core::option::Option<simple_event::Event>,
}
/// Nested message and enum types in `SimpleEvent`.
pub mod simple_event {
    #[derive(::serde::Serialize)]
    #[derive(::serde::Deserialize)]
    #[serde(tag = "type")]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "6")]
        #[serde(rename = "device_connected")]
        DeviceConnectedEvent(super::DeviceConnectedEvent),
        #[prost(message, tag = "7")]
        #[serde(rename = "device_disconnected")]
        DeviceDisconnectedEvent(super::DeviceDisconnectedEvent),
        #[prost(message, tag = "8")]
        #[serde(rename = "incoming_data")]
        IncomingDataEvent(super::IncomingDataEvent),
        #[prost(message, tag = "9")]
        #[serde(rename = "value_change")]
        ValueChangeEvent(super::ValueChangeEvent),
        #[prost(message, tag = "10")]
        #[serde(rename = "value_change_applied")]
        ValueChangeAppliedEvent(super::ValueChangeAppliedEvent),
        #[prost(message, tag = "11")]
        #[serde(rename = "path_created")]
        PathCreatedEvent(super::PathCreatedEvent),
        #[prost(message, tag = "12")]
        #[serde(rename = "path_removed")]
        PathRemovedEvent(super::PathRemovedEvent),
        #[prost(message, tag = "13")]
        #[serde(rename = "value_stored")]
        ValueStoredEvent(super::ValueStoredEvent),
        #[prost(message, tag = "14")]
        #[serde(rename = "incoming_introspection")]
        IncomingIntrospectionEvent(super::IncomingIntrospectionEvent),
        #[prost(message, tag = "15")]
        #[serde(rename = "interface_added")]
        InterfaceAddedEvent(super::InterfaceAddedEvent),
        #[prost(message, tag = "16")]
        #[serde(rename = "interface_removed")]
        InterfaceRemovedEvent(super::InterfaceRemovedEvent),
        #[prost(message, tag = "17")]
        #[serde(rename = "interface_minor_updated")]
        InterfaceMinorUpdatedEvent(super::InterfaceMinorUpdatedEvent),
        #[prost(message, tag = "19")]
        #[serde(rename = "device_error")]
        DeviceErrorEvent(super::DeviceErrorEvent),
        #[prost(message, tag = "20")]
        #[serde(rename = "device_registered")]
        DeviceRegisteredEvent(super::DeviceRegisteredEvent),
        #[prost(message, tag = "21")]
        #[serde(rename = "device_deletion_started")]
        DeviceDeletionStartedEvent(super::DeviceDeletionStartedEvent),
        #[prost(message, tag = "22")]
        #[serde(rename = "device_deletion_finished")]
        DeviceDeletionFinishedEvent(super::DeviceDeletionFinishedEvent),
    }
}
