#!/usr/bin/env python3

import argparse
import datetime
import jwt

api_claims = {"appengine": "a_aea", "realm": "a_rma", "housekeeping": "a_ha", "channels": "a_ch", "pairing": "a_pa"}

default_auth_paths = ["^.*$::^.*$"]

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate credentials for various Astarte components")
    parser.add_argument("-t", "--type", type=str, required=True, choices=['pairing', 'housekeeping', 'realm', 'appengine', 'channels'],
        help="The type of credential you want to generate.")
    parser.add_argument("-p", "--private-key", type=str, required=True, help="Path to the private key file for signing "\
        "the Authorization token.")
    parser.add_argument("-e", "--expiry", type=int, required=False, default=300, help="Expiry of the token in seconds. "\
        "If 0, the token never expires. Defaults to 5 minutes. Doesn't apply to pairing credentials.")
    parser.add_argument("-a", "--auth-paths", type=str, required=False, nargs='+', default=default_auth_paths,
        help="Defines a series of regular expressions for path-based authorization.")
    args = parser.parse_args()
    args_map = vars(args)

    with open(args_map["private_key"], "r") as pk:
        private_key_pem = pk.read()

        if args_map["type"] == "channels" and args_map["auth_paths"] == default_auth_paths:
            auth_paths = ["JOIN::.*", "WATCH::.*"]
        else:
            auth_paths = args_map["auth_paths"]
        now = datetime.datetime.utcnow()
        claims = {api_claims[args_map["type"]]: auth_paths, "iat": now}
        expiry = 0 if args_map["type"] == 'pairing' else args_map["expiry"]
        if expiry > 0:
            claims["exp"] = now + datetime.timedelta(seconds=expiry)

        encoded = jwt.encode(claims, private_key_pem, algorithm="RS256")
        print("{0}".format(encoded.decode()))
