#
# This file is part of Astarte.
#
# Copyright 2026 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

defmodule Astarte.RealmManagement.Generators.InterfaceUtils do
  @moduledoc """
  Generic utils to interact with interfaces generated by Astarte.Core.Generators.Interface
  """

  alias Astarte.Core.Interface
  alias Astarte.Core.Mapping

  @max_invalid_stream_values 150

  # This workaround is needed since generators in Astarte 1.2 may create incorrect interfaces,
  # with inconsistencies in the ttl options of the aggregate mappings (bug #1072).
  # This will be properly fixed in 1.3
  def filter_valid_interfaces(%StreamData{} = interface_datastream) do
    interface_datastream |> StreamData.filter(&valid_interface?(&1), @max_invalid_stream_values)
  end

  defp valid_interface?(%Interface{aggregation: aggregation, mappings: mappings}) do
    case aggregation do
      :object ->
        %Mapping{
          database_retention_policy: reference_database_retention_policy,
          database_retention_ttl: reference_database_retention_ttl
        } = Enum.at(mappings, 0)

        Enum.all?(mappings, fn
          %Mapping{
            database_retention_policy: mapping_database_retention_policy,
            database_retention_ttl: mapping_database_retention_ttl
          } ->
            mapping_database_retention_policy == reference_database_retention_policy and
              mapping_database_retention_ttl == reference_database_retention_ttl
        end)

      :individual ->
        true
    end
  end
end
