#
# This file is part of Astarte.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

defmodule Astarte.Pairing.FDO.OwnerOnboarding.Done2 do
  @moduledoc """
  TO2.Done2 (Type 71).
  From Owner Onboarding Service to Device ROE.

  This message provides an opportunity for a final ACK after the Owner has invoked
  the System Info block to establish agent-to-server communications.

  Reference Section: 5.5.13 TO2.Done2
  """
  use TypedStruct

  typedstruct enforce: true do
    @typedoc "Structure for TO2.Done2 message."

    # NonceTO2SetupDv
    # The Nonce originally generated by the Device and sent to the Owner Service
    # in TO2.SetupDevice.
    # Its presence here serves as a final ACK, proving the Server tracked the session correctly.
    field :nonce_to2_setup_dv, binary()
  end

  @doc """
  Encodes the Done2 struct into CBOR format (binary).
  """
  @spec encode(%__MODULE__{}) :: binary()
  def encode(%__MODULE__{} = p) do
    p
    |> to_cbor_list()
    |> CBOR.encode()
  end

  @doc """
  Converts the struct into a CBOR list for transmission.
  Format: [NonceTO2SetupDv]
  """
  def to_cbor_list(%__MODULE__{} = p) do
    [
      %CBOR.Tag{tag: :bytes, value: p.nonce_to2_setup_dv}
    ]
  end
end
