#
# This file is part of Astarte.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

defmodule Astarte.Pairing.FDO.OwnerOnboarding.ProveDevice do
  @moduledoc """
  TO2.ProveDevice (Type 64).
  From Device ROE to Owner Onboarding Service.

  This message is an EAT (Entity Attestation Token) signed by the Device.
  It proves the provenance of the Device to the new owner and completes the key exchange.

  Reference Section: 5.5.6 TO2.ProveDevice
  """
  use TypedStruct

  typedstruct enforce: true do
    @typedoc "Decoded content of the TO2.ProveDevice EAT."

    # 1. xBKeyExchange
    # The Device's ephemeral public key for the Diffie-Hellman key exchange.
    # Extracted from the EAT Payload: TO2ProveDevicePayload = [ xBKeyExchange ]
    # This completes the key exchange process initiated by the Owner.
    field :xb_key_exchange, binary()

    # 2. NonceTO2ProveDv
    # The Nonce originally sent by the Owner in TO2.ProveOVHdr.
    # Extracted from the EAT Payload Base (EAT-NONCE claim).
    # Used to verify that the Device is responding to the specific challenge from the Owner.
    field :nonce_to2_prove_dv, binary()

    # 3. NonceTO2SetupDv
    # A new Nonce generated by the Device to be used in the next steps (TO2.SetupDevice).
    # Extracted from the COSE Unprotected Headers (EUPHNonce).
    # Note: Unlike the other fields, this is NOT inside the CWT/EAT Payload.
    field :nonce_to2_setup_dv, binary()

    # Optional: The raw EAT token (COSE Sign1 structure).
    # Useful for audit logging or debugging signature verification issues.
    field :raw_eat_token, binary()
  end
end
