# Copyright 2024 SECO Mind Srl
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = "interfaces/**"
precedence = "override"
SPDX-FileCopyrightText = "Copyright 2020 SECO Mind Srl"
SPDX-License-Identifier = "CC0-1.0"