use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# Astarte.AppEngine.APIWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :astarte_appengine_api, Astarte.AppEngine.APIWeb.Endpoint,
  server: true,
  version: Application.spec(:astarte_appengine_api, :vsn)

config :logger, :console,
  format: {PrettyLog.LogfmtFormatter, :format},
  metadata: [
    :method,
    :request_path,
    :status_code,
    :elapsed,
    :realm,
    :module,
    :function,
    :request_id,
    :tag
  ],
  compile_time_purge_matching: [
    [level_lower_than: :info]
  ]

# TODO: handle secret configuration with Conform
# import_config "prod.secret.exs"

config :cqerl,
  cassandra_nodes: [{System.get_env("CASSANDRA_DB_HOST"), System.get_env("CASSANDRA_DB_PORT")}]
