CREATE TABLE :keyspace.to2_sessions (
  guid blob,
  device_id uuid,
  hmac blob,
  nonce blob,
  sig_type int,
  epid_group blob,
  device_public_key blob,
  prove_dv_nonce blob,
  setup_dv_nonce blob,
  kex_suite_name ascii,
  cipher_suite_name int,
  max_owner_service_info_size int,
  owner_random blob,
  secret blob,
  sevk session_key,
  svk session_key,
  sek session_key,
  device_service_info map<tuple<text, text>, blob>,
  owner_service_info list<blob>,
  last_chunk_sent int,
  replacement_guid blob,
  replacement_rv_info blob,
  replacement_pub_key blob,
  replacement_hmac blob,
  PRIMARY KEY (guid)
)
WITH default_time_to_live = 7200;
