defmodule Astarte.Config.HTTPClient do
  @moduledoc """
  Generates an `HTTPoison.Base` client wired to a config generated by
  `Astarte.Config.url_env/4`.

  ```elixir
  defmodule MyApp.ServiceClient do
    use Astarte.Config.HTTPClient, config: MyApp.Config, service: :my_service
  end
  ```
  """

  defmacro __using__(opts) do
    config = Keyword.fetch!(opts, :config)
    service = Keyword.fetch!(opts, :service)

    url_call = {{:., [], [config, :"#{service}_url!"]}, [], []}
    opts_call = {{:., [], [config, :"#{service}_request_opts!"]}, [], []}

    quote do
      use HTTPoison.Base

      @impl true
      def process_request_url(url) do
        unquote(url_call) <> url
      end

      @impl true
      def process_request_options(options) do
        Config.Reader.merge(unquote(opts_call), options)
      end
    end
  end
end
